CREATE TABLE IF NOT EXISTS `properties` (
    `property_id` INT NOT NULL AUTO_INCREMENT,
    `owner_citizenid` VARCHAR(50) NULL,
    `street` VARCHAR(100) NULL,
    `region` VARCHAR(100) NULL,
    `description` LONGTEXT NULL,
    `has_access` JSON NULL DEFAULT (JSON_ARRAY()),
    `access_data` JSON NULL DEFAULT (JSON_ARRAY()),
    `extra_imgs` JSON NULL DEFAULT (JSON_ARRAY()),
    `furnitures` JSON NULL DEFAULT (JSON_ARRAY()),
    `furniture_mode` VARCHAR(16) NOT NULL DEFAULT 'player',
    `storage_data` JSON NULL DEFAULT NULL,
    `wardrobe_data` JSON NULL DEFAULT NULL,
    `for_sale` BOOLEAN NOT NULL DEFAULT 1,
    `price` INT NOT NULL DEFAULT 0,
    `shell` VARCHAR(50) NOT NULL,
    `apartment` VARCHAR(50) NULL DEFAULT NULL,
    `door_data` JSON NULL DEFAULT NULL,
    `garage_data` JSON NULL DEFAULT NULL,
    `zone_data` JSON NULL DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`property_id`),
    UNIQUE KEY `UQ_owner_apartment` (`owner_citizenid`, `apartment`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
